// app/layout.js

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { vazir } from "./font.js";
import Header from "@/app/components/Header";
import { ThemeProvider } from "@/app/components/theme-provider"; // [!code focus]

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // زبان به فارسی تغییر یافت و برای جلوگیری از خطای Hydration از suppressHydrationWarning استفاده شد
    <html
      className={vazir.variable}
      lang="fa"
      dir="rtl"
      suppressHydrationWarning // [!code focus]
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ThemeProvider کل برنامه را در بر می‌گیرد */}
        <ThemeProvider // [!code focus]
          attribute="class" // [!code focus]
          defaultTheme="system" // [!code focus]
          enableSystem // [!code focus]
          disableTransitionOnChange // [!code focus]
        >
          <Header />
          {/* افزودن یک padding-top به main تا محتوا زیر هدر نرود */}
          <main className="pt-24">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
